### PR TITLE
Update 0_multiply.py

### PR DESCRIPTION
**Pull request by jihoBak**
support Python 3.3+

### CODE REVIEW

**Comment by hunkim** [comment]
As mentioned by @nlintz "I'd prefer to not have one off changes to have compatability with python 3. Would you mind updating all of the files to meet compatibility before I merge in your pr?" in #7 

Could you update all files?

**Comment by nlintz** [comment]
@hunkim is correct, please submit a pr in a separate branch with all python 3 compat changes.

**Comment by hunkim** [comment]
@jihoBak I'll close this PR for now. If you could submit a new PR based on @nlintz's comment, it would be greatly appreciated.

**Comment by jihoBak** [comment]
Okay, I'll try it soon!

**Comment by hunkim** [comment]
@jihoBak Thanks! Look forward to.

**Pull request closed without merging**
