### PR TITLE
Update 00_multiply.py to TensorFlow r1.0.0-rc0

### PR DESCRIPTION
**Pull request by ruzrobert**
From r1.0.0-rc0 there is tf.multiply , not tf.mul.

### CODE REVIEW

**Comment by hunkim** [comment]
@ruzrobert Really appreciate your change for TF 1.0. Could you also change the note code?

**Comment by ruzrobert** [comment]
@hunkim Sure, I've made the second pull request.

**Comment by hunkim** [comment]
@ruzrobert No need to create a new PR. Just make an additional change in ruzrobert:patch-1, and push to your repos. Then, it will automatically update this PR. Do you want to try?

**Comment by ruzrobert** [comment]
@hunkim 
Sure! That was hard, but looks like I've succeded. Check pending.

_Also, could you help me with a question in Issues tab? Thank you._

**Comment by hunkim** [comment]
Cool. Thanks!
@ruzrobert I'll check out the issue.

**Pull request merged**
