### PR TITLE
visualizing output in autoencoder

### PR DESCRIPTION
**Pull request by chahuja**

### CODE REVIEW

**Comment by hunkim** [comment]
Super!

1. I really like ipynb, but could you rename it to 06.....ipynb? (Also, could you add ipynb for other files?)

2. For ipynb, could you add results and simple vis output? 
From https://github.com/chahuja/TensorFlow-Tutorials/blob/9cf71d045ad06af5166aca0f4e512b4224804346/autoencoder.ipynb, I can only see the in, but no outputs.

**Comment by chahuja** [comment]
The ipynb version is not yet ready. It needs the addition of noise for a denoising autoencoder. I could add them as and when they get ready.

Also, the images are stored as in_vis.png and pred_vis.png and are included as a function in 06_autoencoder.py

**Comment by hunkim** [comment]
Do you think you can fix this?

```bash
Traceback (most recent call last):
  File "06_autoencoder.py", line 81, in <module>
    vis(predicted_imgs,'pred')
  File "06_autoencoder.py", line 15, in vis
    ax = plt.subplot(g)
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1029, in subplot
    fig = gcf()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/python/2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by chahuja** [comment]
Added `matplotlib.use('Agg')` to bypass using xserver for display

**Comment by hunkim** [comment]
Cool!

**Pull request merged**
