### PR TITLE
Renamed files and changed README for better browsing on Github

### PR DESCRIPTION
**Pull request by florianletsch**
1. Renamed files so that they are displayed in the correct order on Github: `1_foo.py` -> `01_foo.py`
2. Topic items in README.md link to `*.py` files directly

### CODE REVIEW

**Comment by hunkim** [comment]
Looks good to me.

**Comment by hunkim** [comment]
However, the travis fails. Can you modify the .travis file? Thanks!

**Comment by florianletsch** [comment]
Thanks. Hm, my change doesn't seemed to fix it. Might have time to look at that later. Does anyone else see what's wrong in `.travis.yml`?

**Comment by hunkim** [comment]
I think 3_net.py->03_net.py. ? -> ??.

**Comment by florianletsch** [comment]
Yeah, that's what I tried (see the commit I added).

**Comment by hunkim** [comment]
I think it's something else: 

print ckpt.model_checkpoint_path
             ^
SyntaxError: Missing parentheses in call to 'print'

I'll fix it later. 

Thanks for this PR.

**Pull request merged**
