### PR TITLE
Refactor for tensorflow-1.0rc1

### PR DESCRIPTION
**Pull request by normanheckscher**
tf.mul() -> tf.multiply()

### CODE REVIEW

**Comment by hunkim** [comment]
Cool. Thanks!

**Comment by normanheckscher** [comment]
No worries.

Do you think you could create a branch from late November 2016 and call it tf-0.12.1 so that a point is saved for the old library?

**Comment by nlintz** [comment]
Nice job getting compatibility with 1.0. This is awesome! Such a big release :+1:

**Comment by normanheckscher** [comment]
After watching most of the TensorFlow Dev Summit 2017 videos, I think there is a need to use named arguments with all tf python functions. If my understanding of what was said is correct, this will allow for backward compatibility as we move forward with 2.0 & 3.0 & etc releases.

**Pull request merged**
