### PR TITLE
Fixed tensorflow 0.9 API compatibility

### PR DESCRIPTION
**Pull request by j-min**
Fixed tensorflow 0.9 API compatibility
1. replaced "from tensorflow.models.rnn import rnn, rnn_cell" with "tf.nn.rnn_cell"
2. added state_is_tuple=True (https://www.tensorflow.org/versions/r0.9/api_docs/python/nn.html#recurrent-neural-networks)
3. using dtype=tf.float32 instead of init_state

### CODE REVIEW

**Comment by hunkim** [comment]
Travis failed. Can you check? Thanks.

**Comment by j-min** [comment]
According to https://github.com/nlintz/TensorFlow-Tutorials/blob/master/.travis.yml
this repository is based on tensorflow 0.8.0 environment where rnn modules do not accept 'state_is_tuple' argument.

'  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl;'

One of the reason I made this commit is that not using 'state_is_tuple' makes error
`WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x101e360b8>:
Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.`

Can we update our travis environment?

**Comment by hunkim** [comment]
Can you just change 0.8to 0.9 in travis file?

**Comment by j-min** [comment]
Ok then I'll make another pull request with both of the files changed

**Comment by j-min** [comment]
I think we first need to merge .travis.yml separately, so that Travis CI can actually check if new 07_lstm.py can work properly on the new version of tensorflow.

**Comment by hunkim** [comment]
Can you change 
tensorflow-0.8.0-c -> tensorflow-0.9.0-... 

in travis.yml?

**Comment by hunkim** [comment]
Looks good.

**Pull request merged**
