### PR TITLE
Denoising Autoencoder

### PR DESCRIPTION
**Pull request by regata**
Based on the following tutorial http://deeplearning.net/tutorial/dA.html

### CODE REVIEW

**Comment by regata** [comment]
@nlintz what do you think about this PR? I can do more tutorials if you are interested

**Comment by hunkim** [comment]
@regata I really like your PR. However, it seems @nlintz is not very active. Should we start a new simple example repos, perhaps your fork? I really like the simplicity of these examples and yours.

**Comment by knmnyn** [comment]
@regata @hunkim you can use the fork that I built if you want.  I've already pulled both of your PRs into my fork at WING-NUS/TensorFlow-Tutorials.

**Comment by nlintz** [comment]
Hi everyone, sorry for being MIA the last couple of months. These PRs look fantastic, I'm merging them in today.

**Comment by hunkim** [comment]
Super great! Thanks Nathan!

**Pull request merged**
